"""add conditions column to rules

Revision ID: 3bc54eefb279
Revises: 
Create Date: 2025-05-14 17:06:09.303206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc54eefb279'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('conditions', sa.JSON(), nullable=True))
    op.drop_column('rules', 'data_field')
    op.drop_column('rules', 'match_type')
    op.drop_column('rules', 'pattern')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('pattern', sa.VARCHAR(), nullable=True))
    op.add_column('rules', sa.Column('match_type', sa.VARCHAR(), nullable=True))
    op.add_column('rules', sa.Column('data_field', sa.VARCHAR(), nullable=True))
    op.drop_column('rules', 'conditions')
    # ### end Alembic commands ###
