"""Add threshold fields to rules

Revision ID: 9aca4e889a97
Revises: 3bc54eefb279
Create Date: 2025-05-14 18:15:42.333371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aca4e889a97'
down_revision: Union[str, None] = '3bc54eefb279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('threshold_count', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('threshold_window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'threshold_window')
    op.drop_column('rules', 'threshold_count')
    # ### end Alembic commands ###
