"""Add sequence fields to rules

Revision ID: aee674d66cc8
Revises: 9aca4e889a97
Create Date: 2025-05-14 18:28:21.533205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee674d66cc8'
down_revision: Union[str, None] = '9aca4e889a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('sequence', sa.JSON(), nullable=True))
    op.add_column('rules', sa.Column('sequence_window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'sequence_window')
    op.drop_column('rules', 'sequence')
    # ### end Alembic commands ###
